# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: ["--line-length=120"]
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: # arguments to configure flake8
            # making isort line length compatible with black
            - "--max-line-length=120"
            - "--max-complexity=18"

            # these are errors that will be ignored by flake8
            # check out their meaning here
            # https://flake8.pycqa.org/en/latest/user/error-codes.html
            - "--ignore=E203,E266,E501,W503,F403,F401,E402"

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length", "120"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
    -   id: mypy
        entry: bash -c 'mypy "$@" || true' --
        args: ["--warn-unused-ignores"]
